name: Build Image

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    uses: subedi-labs/platform/.github/workflows/build-image-buildpacks.yml@main
    with:
      image_name: TEST-image
      image_tag: ''
      builder: ''
      working_directory: '.'
      env_vars: ''
    permissions:
      contents: read
      packages: write
