name: Build App

on:
  push:
    branches: [main]

jobs:
  build:
    uses: subedi-labs/platform/.github/workflows/build-image-buildpacks.yml@main
    with:
      image_name: my-app
      image_tag: ''
      builder: ''
      working_directory: '.'
      env_vars: ''
    permissions:
      contents: read
      packages: write
